version: '3.7'
services:
  hmc_server:
    container_name: hmc_server
    image: node:18.13.0
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - ./server:/server
    working_dir: /server
    command: bash -c "npm i && npm run server"
